services:
  - type: web
    name: secure-software-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_NAME
        value: adminsoftware-developement
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: /etc/secrets/firebase-adminsdk.json
